# Generated by Django 4.0.4 on 2023-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('creneau', models.CharField(max_length=100)),
                ('reservation_valide',  models.CharField(max_length=200)),
            ],
        ),
    ]
