# Generated by Django 4.0.4 on 2023-11-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='addresse',
            new_name='adresse',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
    ]
