# Generated by Django 4.0.4 on 2023-11-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.user'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
