# Generated by Django 4.0.4 on 2023-11-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '__first__'),
        ('restaurant', '0002_rename_addresse_restaurant_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.user'),
            preserve_default=False,
        ),
    ]
